server:
  type: default

#metrics:
#  reporters:
#    - type: console
#      timeZone: UTC
#      output: stdout

logging:
  level: INFO
  loggers:
    org.leleuj.testdw: INFO
  appenders:
    - type: console